site_name: AZ-305
nav:
    - Home: index.md
    - Study notes: 
       - Pre-requisites: 
          - Home: Prerequisites/index.md
          - Core architectural components: Prerequisites/core-architectural-components.md
          - Security: Prerequisites/security.md       
       - Design identity, governance, and monitoring solutions:
          - Home: Design identity, governance, and monitoring solutions/index.md
          - Governance: Design identity, governance, and monitoring solutions/governance.md
          - Authentication & authorization: Design identity, governance, and monitoring solutions/authentication and authorization.md
          - Log & monitor: Design identity, governance, and monitoring solutions/log and monitor.md
       - Design business continuity solutions:
          - Home: Design business continuity solutions/index.md
          - High availability - Disaster recovery: Design business continuity solutions/HADR.md
          - Backup: Design business continuity solutions/backup.md
       - Design data storage solutions:
          - Home: Design data storage solutions/index.md
          - Relational data: Design data storage solutions/relational-data.md
          - Non-relational data: Design data storage solutions/non-relational-data.md
          - Data integration: Design data storage solutions/data-integration.md 
       - Design infrastructure solutions:
          - Home: Design infrastructure solutions/index.md
          - Compute services: Design infrastructure solutions/compute.md
       - Azure well-architected framework: 
          - Azure well-architected framework/index.md
       - Microsoft cloud adoption framework for Azure: 
          - Microsoft cloud adoption framework for Azure/index.md